pp_topic: /pp_cmd_vel
ftg_topic: /ftg_cmd_vel
scan_topic: /scan_obstacles
cmd_topic: /cmd_vel
danger_distance: 1.20
stop_distance: 0.45
blend_distance: 2.20
clear_path_speed_scale: 1.00
danger_speed_scale: 0.45
max_linear_x: 1.00
max_angular_z: 1.60
