scan_topic: /scan_obstacles
cmd_topic: /cmd_vel_ftg_raw
danger_distance: 0.85
stop_distance: 0.35
front_angle_deg: 85.0
bubble_radius_idx: 10
gap_threshold: 0.85
max_speed: 0.55
min_speed: 0.12
max_angular_z: 1.60
