pp_topic: /cmd_vel_auto
ftg_topic: /cmd_vel_ftg_raw
scan_topic: /scan_obstacles
enable_topic: /auto_enable
cmd_topic: /cmd_vel_safety
danger_distance: 0.85
stop_distance: 0.35
blend_distance: 1.20
clear_path_speed_scale: 1.00
danger_speed_scale: 0.40
max_linear_x: 0.70
max_angular_z: 1.60
publish_hz: 20.0
front_fov_deg: 80.0
publish_zero_once_on_disable: true
